M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu22.04.1} date Wed 11 Jan 2023 08:48:23 AM PST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-11T08:48:23-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X49.4Y-75.1
X50.0Y-48.0
X70.0Y-48.0
X70.6Y-75.1
T2
X24.5Y-44.5
X24.5Y-130.5
X82.5Y-44.5
X82.5Y-130.5
T0
M30
